runtime: python39

instance_class: F1

handlers:
# favicon
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
  expiration: "0"
  secure: always

# Static Files
- url: /static
  secure: always
  static_dir: static
  expiration: "365d"
  http_headers:
    Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
    X-Frame-Options: DENY
    X-XSS-Protection: 1; mode=block
    X-Content-Type-Options: nosniff

# Home Page
- url: /
  secure: always
  static_files: index.html
  upload: index.html
  http_headers:
    Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
    X-Frame-Options: DENY
    X-XSS-Protection: 1; mode=block
    X-Content-Type-Options: nosniff
